config/routes.rb
Rails.application.routes.draw do
  resources :adts
  resources :announcemnts do
    collection do
      get :search
    end
  end
  get 'mapping/index'
  resources :events
  resources :reservists do
    collection do
      get :search
    end
    member do
      get :export_pdf
      patch :activate
    end
  end

  # devise_for :users
  devise_for :users, controllers: {
  sessions: 'users/sessions'
  }
  get  "verify_otp", to: "otp#new"
  post "verify_otp", to: "otp#create"

  get 'home/index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/reservist.rb
class Reservist < ApplicationRecord
    belongs_to :user, optional: true
    has_many :adts, class_name: "Adt", foreign_key: "reservist_id", dependent: :destroy

    def full_name
      "#{last_name}, #{first_name} #{middle_name}"
    end
end

app/controllers/reservists_controller.rb
class ReservistsController < ApplicationController
  before_action :authenticate_user!, except: [:new]
  before_action :set_reservist, only: %i[ show edit update destroy ]
  layout "registration", only: [:new]
  # GET /reservists or /reservists.json
  def index
    @reservists = Reservist.all
  end

  # GET /reservists/1 or /reservists/1.json
  def show
  end

  # GET /reservists/new
  def new
    @reservist = Reservist.new
  end

  # GET /reservists/1/edit
  def edit
  end

  # POST /reservists or /reservists.json
  def create
    @reservist = Reservist.new(reservist_params)

    respond_to do |format|
      if @reservist.save
        format.html { redirect_to @reservist, notice: "Reservist was successfully created." }
        format.json { render :show, status: :created, location: @reservist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @reservist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reservists/1 or /reservists/1.json
  def update
    respond_to do |format|
      if @reservist.update(reservist_params)
        format.html { redirect_to @reservist, notice: "Reservist was successfully updated." }
        format.json { render :show, status: :ok, location: @reservist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @reservist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservists/1 or /reservists/1.json
  def destroy
    @reservist.destroy!

    respond_to do |format|
      format.html { redirect_to reservists_path, status: :see_other, notice: "Reservist was successfully destroyed." }
      format.json { head :no_content }
    end
  end
  
  def search
    results = Geocoder.search(
      params[:query],
      params: {
        countrycodes: "ph", # Philippines only
        addressdetails: 1,
        limit: 5
      }
    )
        
    render json: results.map { |r|
      {
        label: r.display_name,
        latitude: r.latitude,
        longitude: r.longitude,
        city: r.city,
        province: r.province || r.state,
        zipcode: r.postal_code
      }
    }
    
  end


  def export_pdf
    @reservist = Reservist.find(params[:id])

    respond_to do |format|
      format.pdf do
        render pdf: "reservist_#{@reservist.last_name}",
          template: "reservists/pdf",
          formats: [:html],
          layout: "pdf",
          disposition: "attachment",
          encoding: "UTF-8",
          enable_local_file_access: true
      end
    end
  end

  def activate
    @reservist = Reservist.find(params[:id])
    if @reservist.update(is_active: !@reservist.is_active)
      redirect_to reservists_path, notice: "Reservist status updated successfully."
    else
      redirect_to reservists_path, alert: "Failed to update reservist status."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reservist
      @reservist = Reservist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reservist_params
      params.require(:reservist).permit(:rank, :last_name, :first_name, :middle_name, :branch_of_service, :afpsn, :primary_afsc, :duty_afsc, :other_skills, :source_of_enlistment, :soe_authority, :soe_date_of_enlistment, :soe_initial_rank, :source_of_commission, :soc_authority, :soc_date_of_enlistment, :soc_initial_rank, :reservist_classification, :classification_authority, :date_of_classification, :reserve_unit_assignment, :date_assigned, :unit_capability, :present_designation, :mobilization_center, :street_address, :city, :province, :region, :zip_code, :date_of_birth, :place_of_birth, :age, :sex, :marital_status, :religion, :ethnic_group, :blood_type, :eye_color, :hair_color, :complexion, :identifying_marks, :height_cm, :weight_kg, :email, :residence_tel, :office_tel, :mobile_nr, :tin, :sss_number, :gsis_number, :philhealth_number, :pagibig_number, :dialects_spoken, :latitude, :longitude, :lat, :long, :location, :is_active)
    end
end

app/helpers/reservists_helper.rb
module ReservistsHelper
end

app/views/reservists/edit.html.haml
%section.section
  .section-header.d-mobile-none
    .page-description.d-flex.align-items-center
      %h1.flex-grow-1
        Editing Reservist
    .section-header-breadcrumb
      .breadcrumb-item 
        = link_to 'Dashboard', '/'
      .breadcrumb-item
        @reservist

  .col-12.col-md-12.col-lg-12
    .card
      .card-body.p-0
        = render 'form'

- content_for(:page_title, 'Dashboard')

app/views/reservists/index.html.haml
.app-content
  .content-wrapper
    .container
      .card
        .card-header.d-flex
          -# %i.material-icons-two-tone> book
          %h5.card-title
            Reservist List
          %div.ms-auto.d-flex.gap-2
            %a.d-none.d-sm-inline-block.btn.btn-sm.btn-success.shadow-sm{:href => "#"}
              %i.material-icons.me-1 download
              Download

        .card-body
          .datatable-container
            .table-responsive.datatable-container
              %table#vehicles-table.table.table-striped.table-bordered.table-hover.table-sm.datatable
                %thead.bg-light
                  %tr
                    %th Sq.
                    %th Afpsn
                    %th Rank
                    %th Fullname
                    %th Location
                    %th Mobile Nr
                    %th Account Status
                  %th Action
                %tbody
                  - i = 1
                  - @reservists.each do |reservist|
                    %tr.odd{ role: "row" }
                      %td= i
                      %td= reservist.afpsn
                      %td= reservist.rank
                      %td= reservist.full_name
                      %td= reservist.location
                      %td= reservist.mobile_nr
                      %td.text-center
                        - if reservist.is_active
                          %i.material-icons.text-success check
                        - else
                          %i.material-icons.text-danger cancel
                      %td
                        .form-button-action.gap-3.d-flex.justify-content-between.align-items-center
                          - if reservist.is_active
                            = link_to "#",
                              title: "Deactivate",
                              class: "btn btn-danger btn-xs rounded-pill px-2 py-1 small-pill",
                              data: { bs_toggle: "modal", bs_target: "#approveModal-#{reservist.id}" } do
                              Deactivate
                          - else
                            = link_to "#",
                              title: "Activate",
                              class: "btn btn-success btn-xs rounded-pill px-2 py-1 small-pill",
                              data: { bs_toggle: "modal", bs_target: "#approveModal-#{reservist.id}" } do
                              Activate

                          = link_to reservist, title: "Show it", class: "text-primary" do
                            %i.material-icons visibility

                          -# = link_to edit_reservist_path(reservist), title: "Edit it", class: "text-success" do
                          -#   %i.material-icons edit
                          
                        -# = link_to reservist,
                        -#   data: { turbo_method: :delete, turbo_confirm: 'Are you sure?' },
                        -#   title: 'Destroy it',
                        -#   class: 'btn btn-icon btn-sm btn-danger' do
                        -#   %i.material-icons delete
                        .modal.fade{ id: "approveModal-#{reservist.id}", tabindex: "-1", role: "dialog", "aria-labelledby": "approveModalLabel-#{reservist.id}", "aria-hidden": "true" }
                          .modal-dialog
                            .modal-content
                              .modal-header
                                %h5.modal-title{ id: "approveModalLabel-#{reservist.id}" } Confirm Approval
                                %button.btn-close{ type: "button", data: { bs_dismiss: "modal" }, aria: { label: "Close" } }
                              .modal-body
                                Are you sure you want to activate this reservist?
                              .modal-footer
                                - if reservist.is_active
                                  %button.btn.btn-secondary{ type: "button", data: { bs_dismiss: "modal" } } Cancel
                                  = button_to "Yes, Deactivate", activate_reservist_path(reservist), method: :patch, class: "btn btn-danger"
                                - else
                                  %button.btn.btn-secondary{ type: "button", data: { bs_dismiss: "modal" } } Cancel
                                  = button_to "Yes, Activate", activate_reservist_path(reservist), method: :patch, class: "btn btn-success"


                    - i+=1

app/views/reservists/new.html.haml
.app-content
  .container.d-flex.align-items-center.justify-content-center
    .card.border.border-secondary.mx-auto.mt-5.shadow-lg(style="width: 90%;")
      .card-header
        .d-flex.flex-column.align-items-center
          %h4.card-title.w-sm-10 RESERVIST PERSONNEL INFORMATION
          %h4.card-title DATA CAPTURED FORM

      .card-body
        = render "form", reservist: @reservist

app/views/reservists/pdf.html.haml
.title
  RESERVIST PERSONNEL INFORMATION
  %br
  DATA CAPTURED FORM

%table
  %tr.section-header
    %td{colspan: 4} PERSONAL INFORMATION

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Rank
            .field-value= @reservist.rank.presence || "N/A"
          %td
            .field-label Last Name
            .field-value= @reservist.last_name.presence || "N/A"
          %td
            .field-label First Name
            .field-value= @reservist.first_name.presence || "N/A"
          %td
            .field-label Middle Name
            .field-value= @reservist.middle_name.presence || "N/A"

  %tr.field-row
    %td{colspan: 5}
      %table.inner-table
        %tr
          %td
            .field-label Br of Service
            .field-value= @reservist.branch_of_service.presence || "N/A"
          %td
            .field-label AFPSN
            .field-value= @reservist.afpsn.presence || "N/A"
          %td
            .field-label Primary AFSC
            .field-value= @reservist.primary_afsc.presence || "N/A"
          %td
            .field-label Duty AFSC
            .field-value= @reservist.duty_afsc.presence || "N/A"
          %td
            .field-label Other Skills
            .field-value= @reservist.other_skills.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Source of Enlistment
            .field-value= @reservist.source_of_enlistment.presence || "N/A"
          %td
            .field-label Authority
            .field-value= @reservist.soe_authority.presence || "N/A"
          %td
            .field-label Date of Enlistment/Incorporation
            .field-value= @reservist.soe_date_of_enlistment&.strftime("%d/%m/%Y") || "N/A"
          %td
            .field-label Initial Rank
            .field-value= @reservist.soe_initial_rank.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Source of Commission
            .field-value= @reservist.source_of_commission.presence || "N/A"
          %td
            .field-label Authority
            .field-value= @reservist.soc_authority.presence || "N/A"
          %td
            .field-label Date of Commission/Incorporation
            .field-value= @reservist.soc_date_of_enlistment&.strftime("%d/%m/%Y") || "N/A"
          %td
            .field-label Initial Rank
            .field-value= @reservist.soc_initial_rank.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Reservist Classification
            .field-value= @reservist.reservist_classification.presence || "N/A"
          %td
            .field-label Authority
            .field-value= @reservist.classification_authority.presence || "N/A"
          %td
            .field-label Date of Classification
            .field-value= @reservist.date_of_classification&.strftime("%d/%m/%Y") || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Reserve Unit Assignment
            .field-value= @reservist.reserve_unit_assignment.presence || "N/A"
          %td
            .field-label Date Assigned
            .field-value= @reservist.date_assigned&.strftime("%d/%m/%Y") || "N/A"
          %td
            .field-label Unit Capability
            .field-value= @reservist.unit_capability.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Present Designation
            .field-value= @reservist.present_designation.presence || "N/A"
          %td
            .field-label Mobilization Center
            .field-value= @reservist.mobilization_center.presence || "N/A"

  %tr.field-row
    %td{colspan: 5}
      %table.inner-table
        %tr
          %td
            .field-label Home Address(Nr/Street/Brgy)
            .field-value= @reservist.street_address.presence || "N/A"
          %td
            .field-label Town/City
            .field-value= @reservist.city.presence || "N/A"
          %td
            .field-label Province
            .field-value= @reservist.province.presence || "N/A"
          %td
            .field-label Zip Code
            .field-value= @reservist.zip_code.presence || "N/A"
          %td
            .field-label Region
            .field-value= @reservist.region.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Date of Birth (dd/mm/yyyy)
            .field-value= @reservist.date_of_birth&.strftime("%d/%m/%Y") || "N/A"
          %td
            .field-label Age
            .field-value= @reservist.age.presence || "N/A"
          %td
            .field-label Place of Birth (Town/Province)
            .field-value= @reservist.place_of_birth.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Email Address
            .field-value= @reservist.email.presence || "N/A"
          %td
            .field-label Residence Tel Nr
            .field-value= @reservist.residence_tel.presence || "N/A"
          %td
            .field-label Office Tel Nr
            .field-value= @reservist.office_tel.presence || "N/A"
          %td
            .field-label Mobile Nr
            .field-value= @reservist.mobile_nr.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table
        %tr
          %td
            .field-label Ethnic Group
            .field-value= @reservist.ethnic_group.presence || "N/A"
          %td
            .field-label Sex
            .field-value= @reservist.sex.presence || "N/A"
          %td
            .field-label Marital Status
            .field-value= @reservist.marital_status.presence || "N/A"

  %tr.field-row
    %td{colspan: 4}
      %table.inner-table{style: "width: 100%; border-collapse: collapse;"}
        %tr
          %td{rowspan: 3}
            .field-label Religion
            .field-value= @reservist.religion.presence || "N/A"
          %td
            .field-label Blood Type
            .field-value= @reservist.blood_type.presence || "N/A"
          %td
            .field-label Color of Eyes
            .field-value= @reservist.eye_color.presence || "N/A"
          %td
            .field-label Color of Hair
            .field-value= @reservist.hair_color.presence || "N/A"
          %td
            .field-label Complexion
            .field-value= @reservist.complexion.presence || "N/A"
          %td
            .field-label Identifying Marks
            .field-value= @reservist.identifying_marks.presence || "N/A"
        %tr
          %td
            .field-label Weight (kg)
            .field-value= @reservist.weight_kg.presence || "N/A"
          %td
            .field-label TIN
            .field-value= @reservist.tin.presence || "N/A"
          %td
            .field-label SSS Nr
            .field-value= @reservist.sss_number.presence || "N/A"
          %td
            .field-label GSIS Nr
            .field-value= @reservist.gsis_number.presence || "N/A"
          %td
            .field-label PhilHealth Nr
            .field-value= @reservist.philhealth_number.presence || "N/A"
          %td
            .field-label Pag-ibig Nr
            .field-value= @reservist.pagibig_number.presence || "N/A"
        %tr
          %td
            .field-label Height (cm)
            .field-value= @reservist.height_cm.presence || "N/A"
          %td
            .field-label Dialect Spoken
            .field-value= @reservist.dialects_spoken.presence || "N/A"

app/views/reservists/show.html.haml
.app-content
  .container.d-flex.align-items-center.justify-content-center
    .card.border.border-secondary.mx-auto.mt-5.shadow-lg(style="width: 90%;")
      .card-header
        = link_to "Download Profile", export_pdf_reservist_path(@reservist, format: :pdf), class: "btn btn-sm btn-primary float-end"
        .d-flex.flex-column.align-items-center
          %h4.card-title.w-sm-10 RESERVIST PERSONNEL INFORMATION
          %h4.card-title DATA CAPTURED FORM

      .card-body
        .container.gap-3.d-flex.flex-column
          .row
            .col-md-3
              %div
                %label Rank
                %input.form-control{ readonly: true, value: @reservist.rank }
            .col-md-3
              %div
                %label Last Name
                %input.form-control{ readonly: true, value: @reservist.last_name }
            .col-md-3
              %div
                %label First Name
                %input.form-control{ readonly: true, value: @reservist.first_name }
            .col-md-3
              %div
                %label Middle Name
                %input.form-control{ readonly: true, value: @reservist.middle_name }

          .row
            .col-md-3
              %div
                %label Branch of Service
                %input.form-control{ readonly: true, value: @reservist.branch_of_service }
            .col-md-3
              %div
                %label AFPSN
                %input.form-control{ readonly: true, value: @reservist.afpsn }
            .col-md-2
              %div
                %label Primary AFSC
                %input.form-control{ readonly: true, value: @reservist.primary_afsc }
            .col-md-3
              %div
                %label Duty AFSC
                %input.form-control{ readonly: true, value: @reservist.duty_afsc }

          .row
            .col-md-6
              %div
                %label Other Skills
                %textarea.form-control{ readonly: true }= @reservist.other_skills

          .row
            .col-md-3
              %div
                %label Source of Enlistment
                %input.form-control{ readonly: true, value: @reservist.source_of_enlistment }
            .col-md-3
              %div
                %label Authority
                %input.form-control{ readonly: true, value: @reservist.soe_authority }
            .col-md-3
              %div
                %label Date of Enlistment
                %input.form-control{ readonly: true, value: @reservist.soe_date_of_enlistment }
            .col-md-3
              %div
                %label Initial Rank
                %input.form-control{ readonly: true, value: @reservist.soe_initial_rank }

          .row
            .col-md-3
              %div
                %label Source of Commission
                %input.form-control{ readonly: true, value: @reservist.source_of_commission }
            .col-md-3
              %div
                %label SOC Authority
                %input.form-control{ readonly: true, value: @reservist.soc_authority }
            .col-md-3
              %div
                %label SOC Date of Enlistment
                %input.form-control{ readonly: true, value: @reservist.soc_date_of_enlistment }
            .col-md-3
              %div
                %label SOC Initial Rank
                %input.form-control{ readonly: true, value: @reservist.soc_initial_rank }

          .row
            .col-md-4
              %div
                %label Reservist Classification
                %input.form-control{ readonly: true, value: @reservist.reservist_classification }
            .col-md-4
              %div
                %label Classification Authority
                %input.form-control{ readonly: true, value: @reservist.classification_authority }
            .col-md-4
              %div
                %label Date of Classification
                %input.form-control{ readonly: true, value: @reservist.date_of_classification }

          .row
            .col-md-4
              %div
                %label Reserve Unit Assignment
                %input.form-control{ readonly: true, value: @reservist.reserve_unit_assignment }
            .col-md-4
              %div
                %label Date Assigned
                %input.form-control{ readonly: true, value: @reservist.date_assigned }
            .col-md-4
              %div
                %label Unit Capability
                %input.form-control{ readonly: true, value: @reservist.unit_capability }

          .row
            .col-md-6
              %div
                %label Present Designation
                %input.form-control{ readonly: true, value: @reservist.present_designation }
            .col-md-6
              %div
                %label Mobilization Center
                %input.form-control{ readonly: true, value: @reservist.mobilization_center }

          .row
            .col-md-12.pt-3
              %div
                %label Location
                %input.form-control{ readonly: true, value: @reservist.location }

          .row
            .col-md-6.pt-3
              %div
                %label Latitude
                %input.form-control{ readonly: true, value: @reservist.lat }
            .col-md-6.pt-3
              %div
                %label Longitude
                %input.form-control{ readonly: true, value: @reservist.long }

          .row
            .col-md-3
              %div
                %label Street Address
                %input.form-control{ readonly: true, value: @reservist.street_address }
            .col-md-2
              %div
                %label City
                %input.form-control{ readonly: true, value: @reservist.city }
            .col-md-3
              %div
                %label Province
                %input.form-control{ readonly: true, value: @reservist.province }
            .col-md-2
              %div
                %label ZIP Code
                %input.form-control{ readonly: true, value: @reservist.zip_code }
            .col-md-2
              %div
                %label Region
                %input.form-control{ readonly: true, value: @reservist.region }

          .row
            .col-md-3
              %div
                %label Date of Birth
                %input.form-control{ readonly: true, value: @reservist.date_of_birth }
            .col-md-2
              %div
                %label Age
                %input.form-control{ readonly: true, value: @reservist.age }
            .col-md-7
              %div
                %label Place of Birth
                %input.form-control{ readonly: true, value: @reservist.place_of_birth }

          .row
            .col-md-3
              %div
                %label Email
                %input.form-control{ readonly: true, value: @reservist.email }
            .col-md-3
              %div
                %label Residence Tel
                %input.form-control{ readonly: true, value: @reservist.residence_tel }
            .col-md-3
              %div
                %label Office Tel
                %input.form-control{ readonly: true, value: @reservist.office_tel }
            .col-md-3
              %div
                %label Mobile Nr
                %input.form-control{ readonly: true, value: @reservist.mobile_nr }

          .row
            .col-md-3
              %div
                %label Ethnic Group
                %input.form-control{ readonly: true, value: @reservist.ethnic_group }
            .col-md-3
              %div
                %label Sex
                %input.form-control{ readonly: true, value: @reservist.sex }
            .col-md-3
              %div
                %label Marital Status
                %input.form-control{ readonly: true, value: @reservist.marital_status }
            .col-md-3
              %div
                %label Religion
                %input.form-control{ readonly: true, value: @reservist.religion }

          .row
            .col-md-2
              %div
                %label Blood Type
                %input.form-control{ readonly: true, value: @reservist.blood_type }
            .col-md-2
              %div
                %label Eye Color
                %input.form-control{ readonly: true, value: @reservist.eye_color }
            .col-md-2
              %div
                %label Hair Color
                %input.form-control{ readonly: true, value: @reservist.hair_color }
            .col-md-3
              %div
                %label Complexion
                %input.form-control{ readonly: true, value: @reservist.complexion }
            .col-md-3
              %div
                %label Identifying Marks
                %input.form-control{ readonly: true, value: @reservist.identifying_marks }

          .row
            .col-md-3
              %div
                %label Height (cm)
                %input.form-control{ readonly: true, value: @reservist.height_cm }
            .col-md-3
              %div
                %label Weight (kg)
                %input.form-control{ readonly: true, value: @reservist.weight_kg }

          .row
            .col-md-2
              %div
                %label TIN
                %input.form-control{ readonly: true, value: @reservist.tin }
            .col-md-2
              %div
                %label SSS Number
                %input.form-control{ readonly: true, value: @reservist.sss_number }
            .col-md-2
              %div
                %label GSIS Number
                %input.form-control{ readonly: true, value: @reservist.gsis_number }
            .col-md-3
              %div
                %label PhilHealth Number
                %input.form-control{ readonly: true, value: @reservist.philhealth_number }
            .col-md-3
              %div
                %label Pag-IBIG Number
                %input.form-control{ readonly: true, value: @reservist.pagibig_number }

          .row
            .col-md-6
              %div
                %label Dialects Spoken
                %textarea.form-control{ readonly: true }= @reservist.dialects_spoken