config/routes.rb
Rails.application.routes.draw do
  resources :adts
  resources :announcemnts do
    collection do
      get :search
    end
  end
  get 'mapping/index'
  resources :events
  resources :reservists do
    collection do
      get :search
    end
    member do
      get :export_pdf
      patch :activate
    end
  end

  # devise_for :users
  devise_for :users, controllers: {
  sessions: 'users/sessions'
  }
  get  "verify_otp", to: "otp#new"
  post "verify_otp", to: "otp#create"

  get 'home/index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/event.rb
class Event < ApplicationRecord
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: %i[ show edit update destroy ]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  # GET /events/1 or /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events or /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: "Event was successfully created." }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: "Event was successfully updated." }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy!

    respond_to do |format|
      format.html { redirect_to events_path, status: :see_other, notice: "Event was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def event_params
      params.require(:event).permit(:name, :description, :event_date, :location, :event_type)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.haml
= form_for @event do |f|
  - if @event.errors.any?
    #error_explanation
      %h2= "#{pluralize(@event.errors.count, "error")} prohibited this event from being saved:"
      %ul
        - @event.errors.full_messages.each do |message|
          %li= message
  .card
    .card-header
      %div.d-flex.align-items-center
        %h4.card-title
          New Event
    
    .card-body.form-group.mb-0
      .row
        .col-md-6.pt-3
          .field
            = f.label :name
            = f.text_field :name, class: 'form-control', required:  true
        .col-md-6.pt-3
          .field
            = f.label :event_date
            = f.datetime_field :event_date, class: 'form-control', required:  true
        .col-md-6.pt-3
          .field
            = f.label :location
            = f.text_area :location, class: 'form-control', required:  true
        .col-md-6.pt-3
          .field
            = f.label :description
            = f.text_area :description, class: 'form-control', required:  true
        .col-md-6.pt-3
          .field
            = f.label :event_type
            = f.select :event_type,
              [["Training", "training"], ["Seminar", "seminar"]],
              {},
              class: "form-control",
              required: true

      
      .d-flex.pt-4.gap-2.justify-content-end
        = link_to 'Back', events_path, class: 'btn btn-secondary'
        = f.submit 'Save Changes', class: 'btn btn-primary float-right'

app/views/events/edit.html.haml
%section.section
  .section-header.d-mobile-none
    .page-description.d-flex.align-items-center
      %h1.flex-grow-1
        Editing Event
    .section-header-breadcrumb
      .breadcrumb-item 
        = link_to 'Dashboard', '/'
      .breadcrumb-item
        @event

  .col-12.col-md-12.col-lg-12
    .card
      .card-body.p-0
        = render 'form'

- content_for(:page_title, 'Dashboard')

app/views/events/index.html.haml
.app-content
  .content-wrapper
    .container
      .card
        .card-header
          %div.d-flex.align-items-center
            %h4.card-title
              Events
            %div.ms-auto.d-flex.gap-2
              = link_to new_event_path, class: "btn btn-primary btn-round ms-auto btn-sm d-flex align-items-center" do
                %i.material-icons.me-1 add
                Add Event
              %a.d-none.d-sm-inline-block.btn.btn-sm.btn-success.shadow-sm{:href => "#"}
                %i.material-icons.me-1 download
                Download


        .card-body
          .datatable-container
            .table-responsive.datatable-container
              %table#vehicles-table.table.table-striped.table-bordered.table-hover.table-sm.datatable
                %thead.bg-light
                  %tr
                    %th Name
                    %th Description
                    %th Event Date
                    %th Location
                    %th Event Type
                  %th Action
                %tbody
                  - @events.each do |event|
                    %tr.odd{ role: "row" }
                      %td= event.name
                      %td= event.description
                      %td= event.event_date
                      %td= event.location
                      %td= event.event_type
                      
                      %td
                        .form-button-action.gap-3
                          = link_to event, title: "Show it", class: "text-primary" do
                            %i.material-icons visibility

                          = link_to edit_event_path(event), title: "Edit it", class: "text-success" do
                            %i.material-icons edit

                          -# = link_to event,
                          -#   data: { turbo_method: :delete, turbo_confirm: "Are you sure?" },
                          -#   title: "Destroy it",
                          -#   class: "text-danger" do
                          -#   %i.material-icons delete

app/views/events/show.html.haml
.app-content
  .content-wrapper
    .container
      .card
        .card-header
          %div.d-flex.align-items-center.gap-3
            %h4.card-title
              = @event.name
            %span.badge.rounded-pill.bg-primary
              = @event.event_type.titleize
        .card-body
          .row.g-4

            .col-md-6
              %label.form-label.text-muted Event Date
              %p.mb-0
                = @event.event_date.strftime("%B %d, %Y %I:%M %p")

            .col-md-6
              %label.form-label.text-muted Location
              %p.mb-0= @event.location

            .col-12
              %label.form-label.text-muted Description
              .p-3.bg-light.rounded
                = @event.description

        .card-footer.text-end
          = link_to 'Back', events_path, class: "btn btn-light me-2"
          = link_to 'Edit', edit_event_path(@event), class: "btn btn-warning px-4"