config/routes.rb
Rails.application.routes.draw do
  resources :adts
  resources :announcemnts do
    collection do
      get :search
    end
  end
  get 'mapping/index'
  resources :events
  resources :reservists do
    collection do
      get :search
    end
    member do
      get :export_pdf
      patch :activate
    end
  end

  # devise_for :users
  devise_for :users, controllers: {
  sessions: 'users/sessions'
  }
  get  "verify_otp", to: "otp#new"
  post "verify_otp", to: "otp#create"

  get 'home/index'


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/views/layouts/_navbar.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.shadow-sm
  .container-fluid.d-flex.justify-content-between.align-items-center

    / LEFT SIDE (Hamburger + Brand)
    .d-flex.align-items-center
      %button.navbar-toggler.me-2.d-lg-none{
        type: "button",
        "data-bs-toggle" => "offcanvas",
        "data-bs-target" => "#sidebar-mobile"
      }
        %span.navbar-toggler-icon

      %span.navbar-brand.mb-0.text-dark DVS

    / RIGHT SIDE
    .d-flex.align-items-center.ms-auto

      / 🔔 Notifications (Always visible)
      .dropdown.me-2
        %a.nav-link.position-relative{
          href: "#",
          "data-bs-toggle" => "dropdown"
        }
          %i.material-icons notifications
          -# %span.badge.bg-danger.position-absolute.top-0.start-100.translate-middle.rounded-pill
          -#   4

        %ul.dropdown-menu.dropdown-menu-end
          %li.dropdown-header 4 New Notifications
          %li
            %a.dropdown-item{ href: "#" } New user registered
          %li
            %a.dropdown-item{ href: "#" } Rahmad commented
          %li
            %hr.dropdown-divider
          %li
            %a.dropdown-item{ href: "#" } View All

      / 👤 Profile Dropdown (Always visible)
      .dropdown 
    %a.nav-link.dropdown-toggle{
      href: "#",
      "data-bs-toggle" => "dropdown"
    }
      %span.d-none.d-lg-inline Hi,
      %strong.d-none.d-lg-inline
        = current_user.email
      %i.material-icons.d-lg-none account_circle

    %ul.dropdown-menu.dropdown-menu-end
      %li
        %a.dropdown-item{ href: "#" } My Profile
      %li
        %a.dropdown-item{ href: "#" } Account Setting
      %li
        %hr.dropdown-divider
      %li
        = link_to "Logout",
          destroy_user_session_path,
          data: { turbo_method: :delete },
          class: "dropdown-item text-danger"

app/views/layouts/_sidebar.html.haml
%div
  / Sidebar
  -# For desktop, always visible
  #sidebar-desktop.sidebar.bg-dark.d-none.d-lg-block.vh-100
    %ul.nav.d-flex.flex-column.justify-content-center
      %li.nav-item.pt-3.pb-3.d-flex.justify-content-center
        = image_tag "logo.png", class: "d-flex align-items-center justify-content-center gap-2", style: "max-width: 120px;"
      %li.nav-item.p-3{class: "#{'active' if current_page?('/home/index')}"}
        = link_to "/home/index", class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
          %i.material-icons dashboard
          Dashboard
      %li.nav-item.p-3{class: "#{'active' if current_page?('/announcemnts')}"}
        = link_to "/announcemnts",class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
          %i.material-icons campaign
          Emergency Notification
      %li.nav-item.p-3{class: "#{'active' if current_page?('/events')}"}
        = link_to "/events",class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
          %i.material-icons event
          Events
      %li.nav-item.p-3{class: "#{'active' if current_page?('/reservists')}"}
        = link_to "/reservists", class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
          %i.material-icons groups
          Reservists
      %li.nav-item.p-3{class: "#{'active' if current_page?('/mapping/index')}"}
        = link_to "/mapping/index",class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
          %i.material-icons map
          Mapping
      %li.nav-item
        %a.nav-link.d-flex.align-items-center.justify-content-between{
          data: { bs_toggle: "collapse" },
          href: "#eventsSubmenu",
          role: "button",
          aria: { expanded: "false", controls: "eventsSubmenu" }
        }
          .d-flex.align-items-center.gap-2
            %i.material-icons military_tech
            %span ADT

          %i.material-icons.chevron-icon expand_more

        %ul.collapse.list-unstyled.ps-4#eventsSubmenu
          %li
            = link_to "Create Application", new_adt_path, class: "nav-link"
          %li
            = link_to "View Applications", adts_path, class: "nav-link"
      %li.nav-item.p-3
        = button_to destroy_user_session_path, method: :delete, class: 'nav-link btn btn-link p-0 text-start' do
          %i.material-icons logout
          Logout

  -# For mobile, offcanvas sidebar
  #sidebar-mobile.sidebar.offcanvas.offcanvas-start.bg-dark.d-lg-none{ tabindex: "-1" }

    .offcanvas-header
      %h5.offcanvas-title Menu
      %button.btn-close{ class: "text-white", type: "button", data: { bs_dismiss: "offcanvas" } }
    .offcanvas-body.p-0
      %ul.nav.d-flex.flex-column.justify-content-center
        %li.nav-item.pt-3.pb-3.d-flex.justify-content-center
          = image_tag "logo.png", class: "d-flex align-items-center justify-content-center gap-2", style: "max-width: 100px;"
        %li.nav-item.p-3{class: "#{'active' if current_page?('/home/index')}"}
          = link_to "/home/index", class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
            %i.material-icons dashboard
            Dashboard
        %li.nav-item.p-3{class: "#{'active' if current_page?('/events')}"}
          = link_to "/events",class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
            %i.material-icons event
            Events
        %li.nav-item.p-3{class: "#{'active' if current_page?('/reservists')}"}
          = link_to "/reservists", class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
            %i.material-icons groups
            Reservists
        %li.nav-item.p-3{class: "#{'active' if current_page?('/mapping/index')}"}
          = link_to "/mapping/index",class: "nav-link btn btn-link p-0 text-start d-flex align-items-center gap-2" do
            %i.material-icons map
            Mapping
        %li.nav-item
          %a.nav-link.d-flex.align-items-center.justify-content-between{
            data: { bs_toggle: "collapse" },
            href: "#eventsSubmenu",
            role: "button",
            aria: { expanded: "false", controls: "eventsSubmenu" }
          }
            .d-flex.align-items-center.gap-2
              %i.material-icons military_tech
              %span ADT

            %i.material-icons.chevron-icon expand_more

          %ul.collapse.list-unstyled.ps-4#eventsSubmenu
            %li
              = link_to "Create Application", new_adt_path, class: "nav-link"
            %li
              = link_to "View Applications", adts_path, class: "nav-link"
        %li.nav-item.p-3
          = button_to destroy_user_session_path, method: :delete, class: 'nav-link btn btn-link p-0 text-start' do
            %i.material-icons logout
            Logout

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{ charset: "UTF-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    %title DVS
    = csrf_meta_tags
    = csp_meta_tag

    / Fonts & Material Icons
    %link{ href: "https://fonts.gstatic.com", rel: "preconnect" }
    %link{:href => "https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap", :rel => "stylesheet"}/
    %link{ href: "https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp", rel: "stylesheet" }

    / Bootstrap CSS
    %link{ href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css", rel: "stylesheet", crossorigin: "anonymous" }
    %link{:href => "https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css", :rel => "stylesheet", :type => "text/css"}/

    %link{:href => "https://unpkg.com/leaflet@1.9.4/dist/leaflet.css", :rel => "stylesheet"}/
    %script{:src => "https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"}

    %script{:src => "https://cdn.jsdelivr.net/npm/chart.js"}

    = stylesheet_link_tag "application", "data-turbo-track": "reload"

    / Importmap
    = javascript_importmap_tags

  %body{ data: { turbo: "false" } }
    - if user_signed_in?
      .d-flex.flex-column.flex-lg-row.vh-100
        = render "layouts/sidebar"
        .d-flex.flex-column.flex-grow-1.flex-shrink-1{style: "min-width:0; overflow-y:auto;"}
          = render "layouts/navbar"
          / Content area
          .container-fluid{style: "min-width:0; overflow-x:auto;"}
            - if notice
              %p.alert.alert-success= notice
            - if alert
              %p.alert.alert-danger= alert
            = yield

    - else
      .container.pt-5
        .row.justify-content-center
          .col-md-6
            = yield

    / Bootstrap JS bundle (includes Offcanvas)
    %script{ src: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js", crossorigin: "anonymous" }
    

app/views/layouts/pdf.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %style
      :css
        @page {
          size: A4;
          margin: 15mm;
        }

        body {
          font-family: "Times New Roman", serif;
          font-size: 11px;
        }

        .title {
          text-align: center;
          font-weight: bold;
          font-size: 14px;
          margin-bottom: 10px;
        }

        table {
          width: 100%;
          border-collapse: collapse;
        }

        th, td {
          border: 1px solid black;
          padding: 4px;
          vertical-align: top;
        }

        th {
          font-weight: bold;
          text-align: left;
        }

        .section-header {
          background: #bfbfbf;
          font-weight: bold;
        }

        .center {
          text-align: center;
        }

        .field-row td {
         padding: 0;
        }

        .inner-table {
          width: 100%;
          border-collapse: collapse;
        }

        .inner-table td {
          border-right: 1px solid black;
          padding: 4px;
          vertical-align: top;
        }

        .inner-table td:last-child {
          border-right: none;
        }

        .field-label {
          font-weight: bold;
          font-size: 10px;
          margin-bottom: 2px;
        }

        .field-value {
          min-height: 14px;
        }


  %body
    = yield

app/views/layouts/registration.html.haml
!!!
%html
  %head
    %meta{ charset: "UTF-8" }
    %meta{ name: "viewport", content: "width=device-width, initial-scale=1" }
    %title DVS
    = csrf_meta_tags
    = csp_meta_tag

    / Fonts & Material Icons
    %link{ href: "https://fonts.gstatic.com", rel: "preconnect" }
    %link{:href => "https://fonts.googleapis.com/css2?family=Public+Sans:wght@300;400;500;600;700&display=swap", :rel => "stylesheet"}/
    %link{ href: "https://fonts.googleapis.com/css?family=Material+Icons|Material+Icons+Outlined|Material+Icons+Two+Tone|Material+Icons+Round|Material+Icons+Sharp", rel: "stylesheet" }

    / Bootstrap CSS
    %link{ href: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css", rel: "stylesheet", crossorigin: "anonymous" }

    = stylesheet_link_tag "application", "data-turbo-track": "reload"

    / Importmap
    = javascript_importmap_tags

  %body{ data: { turbo: "false" } }
    .d-flex.flex-column.flex-lg-row.vh-100.vw-100
      .d-flex.flex-column.flex-grow-1.flex-shrink-1{style: "min-width:0; overflow-y:auto;"}
        .container-fluid{style: "min-width:0; overflow-x:auto;"}
          - if notice
            %p.alert.alert-success= notice
          - if alert
            %p.alert.alert-danger= alert
          = yield

    / Bootstrap JS bundle (includes Offcanvas)
    %script{ src: "https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js", crossorigin: "anonymous" }
    